### ISSUE TITLE
Dont work and web one no codes???

### ISSUE THREAD

**Issue by Lucas2299** [AllCoinLab/AutoShill#10]
How can i get it work in windows 
and web one has no codes to execute

**Comment by Lucas2299** [comment]
I got it work in web but only 5 telegram channels got there and it not taking mine

**Comment by AllCoinLab** [comment]
https://docs.theweb3project.com/ecosystem/other-utilities/extras/autoshill-tool/how-to-use-autoshill
it requires some basic channels to be joined + your groups will be joined soon
there is a join limit per day
\
