### ISSUE TITLE
VIRUS TOTAL DETECTED AS MALICIOUS

### ISSUE THREAD

**Issue by alansheard** [AllCoinLab/AutoShill#6]
https://www.virustotal.com/gui/file/79c8744bdfe6434f705233abba8567cf1b103efc7f6caa69ce89f8e1069c2942

**Comment by AllCoinLab** [comment]
if you search for them, they usually gives false alarm to make u to buy their solution
and i couldn't solve it for u, u should run ur own virus detector and remove it. sorry
